#pragma once

#define OPTIONAL_NO_VALUE (0)
#define OPTIONAL_HAS_VALUE (1)

#define OPTIONAL_HAS_VALUE_STRUCT_INDEX (0)
#define OPTIONAL_ELEMENT_TYPE_STRUCT_INDEX (1)

#define OPTIONAL_ELEMENT_COUNT (2)